/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useMemo } from 'react';
import { 
  Scale, 
  TrendingDown, 
  TrendingUp, 
  CheckCircle2, 
  Clock, 
  Search, 
  Filter, 
  Calendar, 
  User, 
  FileSpreadsheet, 
  Plus, 
  AlertCircle, 
  Check, 
  X, 
  ChevronRight, 
  DollarSign, 
  Layers, 
  ShieldCheck,
  CreditCard,
  Receipt,
  FileText
} from 'lucide-react';
import { PumperShortageExcessRecord, Employee, Shift, AuthUser } from '../types';
import { supabase } from '../lib/supabase';
import { 
  fetchPumperShortagesExcess, 
  savePumperShortageExcessRecords, 
  updatePumperShortageExcessStatus 
} from '../lib/supabaseClient';

interface PumperShortExcessTabProps {
  employees: Employee[];
  shiftHistory?: Shift[];
  activeShift?: Shift | null;
  user?: AuthUser | null;
}

export default function PumperShortExcessTab({
  employees,
  shiftHistory = [],
  activeShift,
  user
}: PumperShortExcessTabProps) {
  const [records, setRecords] = useState<PumperShortageExcessRecord[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [toastMessage, setToastMessage] = useState<{ text: string; type: 'success' | 'error' | 'info' } | null>(null);

  // Filter states
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedPumperFilter, setSelectedPumperFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState<'all' | 'PENDING' | 'SETTLED'>('all');
  const [typeFilter, setTypeFilter] = useState<'all' | 'SHORTAGE' | 'EXCESS' | 'BALANCED'>('all');
  const [dateRangeFilter, setDateRangeFilter] = useState<'all' | 'today' | '7days' | 'month' | 'custom'>('all');
  const [customDate, setCustomDate] = useState<string>('');

  // Settlement Modal State
  const [settlementModalRecord, setSettlementModalRecord] = useState<PumperShortageExcessRecord | null>(null);
  const [settlementNotes, setSettlementNotes] = useState('');
  const [isSubmittingSettlement, setIsSubmittingSettlement] = useState(false);

  // Manual Entry / Adjustment Modal State
  const [isAddAdjustmentOpen, setIsAddAdjustmentOpen] = useState(false);
  const [adjustmentForm, setAdjustmentForm] = useState({
    pumperId: '',
    shiftId: '',
    date: new Date().toISOString().slice(0, 10),
    expectedAmount: 0,
    collectedAmount: 0,
    status: 'PENDING' as 'PENDING' | 'SETTLED',
    notes: ''
  });

  // Details Modal State
  const [detailRecord, setDetailRecord] = useState<PumperShortageExcessRecord | null>(null);

  const showToast = (text: string, type: 'success' | 'error' | 'info' = 'success') => {
    setToastMessage({ text, type });
    setTimeout(() => setToastMessage(null), 4000);
  };

  // Load records on mount & synchronize from closed shifts if needed
  const loadRecords = async (silent = false) => {
    if (!silent) setIsLoading(true);
    else setIsRefreshing(true);

    try {
      let fetched = await fetchPumperShortagesExcess(supabase);

      // If no records in database yet but we have shift history, generate records from shiftHistory pumpReadings
      if (fetched.length === 0 && shiftHistory.length > 0) {
        const autoGenerated: PumperShortageExcessRecord[] = [];
        
        shiftHistory.forEach(s => {
          if (!s.pumpReadings || s.pumpReadings.length === 0) return;
          const shiftDate = s.startTime ? s.startTime.slice(0, 10) : new Date().toISOString().slice(0, 10);
          
          // Group by pumper
          const pumperMap = new Map<string, {
            pumperName: string;
            expected: number;
            actual: number;
          }>();

          s.pumpReadings.forEach(r => {
            if (!r.assignedPumperId) return;
            const pId = r.assignedPumperId;
            const pName = employees.find(e => e.id === pId)?.name || 'Pumper';
            
            const isOil = r.pumpId === 'pump-oil-bay' || r.fuelType === 'Oil & Lubricants';
            const fuelSold = isOil ? 0 : Math.max(0, (r.endMeter || 0) - (r.startMeter || 0));
            const netSold = isOil ? 0 : Math.max(0, fuelSold - (r.testingQty || 0));
            const unitPrice = r.unitPrice || 0;
            const grossRev = (netSold * unitPrice) + (r.oilSalesAmount || 0);

            const nonCash = (r.creditSalesAmount || 0) + (r.cardSalesAmount || 0) + (r.touchCardSalesAmount || 0) + (r.voucherSalesAmount || 0);
            const actCash = r.actualCash || 0;

            const cur = pumperMap.get(pId) || { pumperName: pName, expected: 0, actual: 0 };
            pumperMap.set(pId, {
              pumperName: pName,
              expected: cur.expected + grossRev,
              actual: cur.actual + (actCash + nonCash)
            });
          });

          pumperMap.forEach((val, pId) => {
            const variance = val.actual - val.expected;
            const rType: 'SHORTAGE' | 'EXCESS' | 'BALANCED' = 
              variance < -0.5 ? 'SHORTAGE' : variance > 0.5 ? 'EXCESS' : 'BALANCED';
            
            autoGenerated.push({
              id: `rec_${s.id}_${pId}`,
              shift_id: s.id,
              shift_name: s.name,
              pumper_id: pId,
              pumper_name: val.pumperName,
              date: shiftDate,
              expected_amount: val.expected,
              collected_amount: val.actual,
              variance_amount: variance,
              type: rType,
              status: rType === 'BALANCED' ? 'SETTLED' : 'PENDING',
              notes: `Auto-generated from Shift ${s.id}`
            });
          });
        });

        if (autoGenerated.length > 0) {
          await savePumperShortageExcessRecords(supabase, autoGenerated);
          fetched = autoGenerated;
        }
      }

      setRecords(fetched);
    } catch (err) {
      console.warn('Error loading pumper shortages/excess:', err);
      showToast('Could not load latest records from server. Using local cache.', 'error');
    } finally {
      setIsLoading(false);
      setIsRefreshing(false);
    }
  };

  useEffect(() => {
    loadRecords();
  }, [shiftHistory, employees]);

  // Handle Settlement Submission
  const handleConfirmSettlement = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!settlementModalRecord) return;
    setIsSubmittingSettlement(true);

    try {
      const settledBy = user?.name || 'Supervisor';
      const updatedNotes = settlementNotes.trim() 
        ? `${settlementModalRecord.notes ? settlementModalRecord.notes + ' • ' : ''}Settled: ${settlementNotes.trim()}`
        : settlementModalRecord.notes;

      const res = await updatePumperShortageExcessStatus(
        supabase,
        settlementModalRecord.id,
        'SETTLED',
        settledBy,
        updatedNotes
      );

      if (res.success) {
        setRecords(prev => prev.map(r => {
          if (r.id === settlementModalRecord.id) {
            return {
              ...r,
              status: 'SETTLED',
              settled_at: new Date().toISOString(),
              settled_by: settledBy,
              notes: updatedNotes
            };
          }
          return r;
        }));
        showToast(`Settlement completed for ${settlementModalRecord.pumper_name}!`, 'success');
        setSettlementModalRecord(null);
        setSettlementNotes('');
      } else {
        showToast('Settlement could not be saved to server.', 'error');
      }
    } catch (err) {
      console.error('Settlement error:', err);
      showToast('An unexpected error occurred during settlement.', 'error');
    } finally {
      setIsSubmittingSettlement(false);
    }
  };

  // Handle Mark as Pending (Re-open)
  const handleReopenRecord = async (record: PumperShortageExcessRecord) => {
    try {
      const res = await updatePumperShortageExcessStatus(supabase, record.id, 'PENDING');
      if (res.success) {
        setRecords(prev => prev.map(r => r.id === record.id ? { ...r, status: 'PENDING', settled_at: undefined, settled_by: undefined } : r));
        showToast(`Record for ${record.pumper_name} marked as Pending Settlement.`, 'info');
      }
    } catch (err) {
      showToast('Could not update status.', 'error');
    }
  };

  // Handle Manual Adjustment Creation
  const handleSaveAdjustment = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!adjustmentForm.pumperId) {
      showToast('Please select a Pumper.', 'error');
      return;
    }

    const pName = employees.find(e => e.id === adjustmentForm.pumperId)?.name || 'Pumper';
    const variance = Number(adjustmentForm.collectedAmount) - Number(adjustmentForm.expectedAmount);
    const rType: 'SHORTAGE' | 'EXCESS' | 'BALANCED' = 
      variance < -0.5 ? 'SHORTAGE' : variance > 0.5 ? 'EXCESS' : 'BALANCED';

    const newRecord: PumperShortageExcessRecord = {
      id: `adj_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
      shift_id: adjustmentForm.shiftId || 'MANUAL-ADJ',
      shift_name: adjustmentForm.shiftId ? `Shift ${adjustmentForm.shiftId}` : 'Manual Adjustment',
      pumper_id: adjustmentForm.pumperId,
      pumper_name: pName,
      date: adjustmentForm.date || new Date().toISOString().slice(0, 10),
      expected_amount: Number(adjustmentForm.expectedAmount),
      collected_amount: Number(adjustmentForm.collectedAmount),
      variance_amount: variance,
      type: rType,
      status: adjustmentForm.status,
      settled_by: adjustmentForm.status === 'SETTLED' ? (user?.name || 'Supervisor') : undefined,
      settled_at: adjustmentForm.status === 'SETTLED' ? new Date().toISOString() : undefined,
      notes: adjustmentForm.notes || 'Direct Supervisor Balance Entry',
      created_at: new Date().toISOString()
    };

    try {
      await savePumperShortageExcessRecords(supabase, [newRecord]);
      setRecords(prev => [newRecord, ...prev]);
      showToast(`Adjustment record saved for ${pName}!`, 'success');
      setIsAddAdjustmentOpen(false);
      setAdjustmentForm({
        pumperId: '',
        shiftId: '',
        date: new Date().toISOString().slice(0, 10),
        expectedAmount: 0,
        collectedAmount: 0,
        status: 'PENDING',
        notes: ''
      });
    } catch (err) {
      showToast('Error saving manual adjustment record.', 'error');
    }
  };

  // Filtered Records
  const filteredRecords = useMemo(() => {
    const todayStr = new Date().toISOString().slice(0, 10);
    const sevenDaysAgo = new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10);
    const firstDayOfMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10);

    return records.filter(r => {
      // Search
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase().trim();
        const matchesName = r.pumper_name.toLowerCase().includes(q);
        const matchesShift = (r.shift_id || '').toLowerCase().includes(q) || (r.shift_name || '').toLowerCase().includes(q);
        const matchesNotes = (r.notes || '').toLowerCase().includes(q);
        if (!matchesName && !matchesShift && !matchesNotes) return false;
      }

      // Pumper Filter
      if (selectedPumperFilter !== 'all' && r.pumper_id !== selectedPumperFilter) {
        return false;
      }

      // Status Filter
      if (statusFilter !== 'all' && r.status !== statusFilter) {
        return false;
      }

      // Type Filter
      if (typeFilter !== 'all' && r.type !== typeFilter) {
        return false;
      }

      // Date Range Filter
      if (dateRangeFilter === 'today' && r.date !== todayStr) return false;
      if (dateRangeFilter === '7days' && r.date < sevenDaysAgo) return false;
      if (dateRangeFilter === 'month' && r.date < firstDayOfMonth) return false;
      if (dateRangeFilter === 'custom' && customDate && r.date !== customDate) return false;

      return true;
    });
  }, [records, searchQuery, selectedPumperFilter, statusFilter, typeFilter, dateRangeFilter, customDate]);

  // Export to CSV helper
  const exportToCSV = () => {
    if (filteredRecords.length === 0) return;
    
    let csv = "Date,Shift ID,Pumper Name,Expected Sales (Rs.),Collected Handover (Rs.),Variance (Rs.),Type,Status,Settled At,Settled By,Notes\n";
    filteredRecords.forEach(r => {
      csv += `"${r.date}","${r.shift_id}","${r.pumper_name}",${r.expected_amount.toFixed(2)},${r.collected_amount.toFixed(2)},${r.variance_amount.toFixed(2)},"${r.type}","${r.status}","${r.settled_at || ''}","${r.settled_by || ''}","${(r.notes || '').replace(/"/g, '""')}"\n`;
    });

    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Pumper_Shortage_Excess_Ledger_${new Date().toISOString().slice(0, 10)}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const pumperList = useMemo(() => {
    return employees.filter(e => e.role?.toLowerCase() === 'pumper' || !e.role || e.role?.toLowerCase() === 'supervisor');
  }, [employees]);

  return (
    <div className="space-y-4 pb-12 font-sans">
      {/* Toast notification banner */}
      {toastMessage && (
        <div className={`fixed bottom-5 right-5 z-50 px-4 py-3 rounded-xl shadow-lg border flex items-center gap-2.5 text-xs font-bold animate-fade-in ${
          toastMessage.type === 'error'
            ? 'bg-rose-50 text-rose-800 border-rose-200'
            : toastMessage.type === 'info'
            ? 'bg-blue-50 text-blue-800 border-blue-200'
            : 'bg-emerald-50 text-emerald-800 border-emerald-200'
        }`}>
          {toastMessage.type === 'error' ? (
            <AlertCircle className="w-4 h-4 text-rose-600" />
          ) : (
            <Check className="w-4 h-4 text-emerald-600" />
          )}
          <span>{toastMessage.text}</span>
        </div>
      )}

      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="space-y-0.5">
          <div className="flex items-center gap-2.5">
            <div className="p-1.5 bg-indigo-50 text-indigo-700 rounded-lg border border-indigo-100">
              <Scale className="w-4.5 h-4.5" />
            </div>
            <div>
              <h1 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight">
                Pumper Shortage &amp; Excess Tracking
              </h1>
              <p className="text-xs text-gray-500 font-medium">
                Shift-wise cash handover audit, pumper variance tracking, and shortage recovery ledger.
              </p>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={exportToCSV}
            disabled={filteredRecords.length === 0}
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 bg-white hover:bg-gray-50 disabled:opacity-50 text-gray-700 border border-gray-200 rounded-xl text-xs font-bold transition-all cursor-pointer shadow-2xs"
          >
            <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-600" />
            <span>Export CSV</span>
          </button>

          <button
            onClick={() => setIsAddAdjustmentOpen(true)}
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold transition-all cursor-pointer shadow-xs hover:shadow-sm active:scale-95"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Record Manual Balance</span>
          </button>
        </div>
      </div>

      {/* Main Ledger Table Card */}
      <div className="bg-white rounded-2xl border border-gray-200/80 shadow-2xs overflow-hidden">
        {/* Toolbar & Filters */}
        <div className="p-4 sm:p-5 border-b border-gray-100 space-y-3.5">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3">
            {/* Search Input */}
            <div className="relative flex-1 max-w-md">
              <Search className="w-4 h-4 text-gray-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Search by pumper, shift ID, or notes..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-9.5 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              />
            </div>

            {/* Filter Dropdowns */}
            <div className="flex items-center gap-2 flex-wrap">
              {/* Pumper Filter */}
              <select
                value={selectedPumperFilter}
                onChange={(e) => setSelectedPumperFilter(e.target.value)}
                className="px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              >
                <option value="all">All Pumpers ({pumperList.length})</option>
                {pumperList.map(p => (
                  <option key={p.id} value={p.id}>{p.name}</option>
                ))}
              </select>

              {/* Status Filter */}
              <select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value as any)}
                className="px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              >
                <option value="all">All Statuses</option>
                <option value="PENDING">Pending Settlement</option>
                <option value="SETTLED">Settled</option>
              </select>

              {/* Type Filter */}
              <select
                value={typeFilter}
                onChange={(e) => setTypeFilter(e.target.value as any)}
                className="px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              >
                <option value="all">All Variance Types</option>
                <option value="SHORTAGE">Shortages (Red)</option>
                <option value="EXCESS">Excesses (Green)</option>
                <option value="BALANCED">Balanced (Exact)</option>
              </select>

              {/* Date Preset Filter */}
              <select
                value={dateRangeFilter}
                onChange={(e) => setDateRangeFilter(e.target.value as any)}
                className="px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              >
                <option value="all">All Time</option>
                <option value="today">Today</option>
                <option value="7days">Last 7 Days</option>
                <option value="month">This Month</option>
                <option value="custom">Specific Date</option>
              </select>

              {dateRangeFilter === 'custom' && (
                <input
                  type="date"
                  value={customDate}
                  onChange={(e) => setCustomDate(e.target.value)}
                  className="px-3 py-1.5 bg-gray-50 border border-gray-200 rounded-xl text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                />
              )}
            </div>
          </div>
        </div>

        {/* Ledger Table */}
        <div className="overflow-x-auto">
          {isLoading ? (
            <div className="py-16 text-center text-xs text-gray-400 font-semibold animate-pulse">
              Loading pumper shortage &amp; excess ledger...
            </div>
          ) : filteredRecords.length === 0 ? (
            <div className="py-16 text-center space-y-2">
              <div className="inline-flex p-3 bg-gray-50 rounded-full text-gray-400">
                <Scale className="w-6 h-6" />
              </div>
              <p className="text-sm font-bold text-gray-700">No pumper variance records found</p>
              <p className="text-xs text-gray-400 max-w-sm mx-auto">
                Records are automatically logged during Shift Closing when individual pumper collections and meter readings are reconciled.
              </p>
            </div>
          ) : (
            <table className="w-full text-left text-xs">
              <thead className="bg-gray-50/80 font-bold text-gray-500 text-[10px] uppercase border-b border-gray-100">
                <tr>
                  <th className="py-2.5 px-3.5">Date &amp; Shift</th>
                  <th className="py-2.5 px-3.5">Pumper Name</th>
                  <th className="py-2.5 px-3.5 text-right">Expected Sales</th>
                  <th className="py-2.5 px-3.5 text-right">Actual Handover</th>
                  <th className="py-2.5 px-3.5 text-right">Shortage / Excess</th>
                  <th className="py-2.5 px-3.5 text-center">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 font-medium text-gray-800">
                {filteredRecords.map((record) => {
                  const isShortage = record.variance_amount < -0.5;
                  const isExcess = record.variance_amount > 0.5;
                  const isBalanced = !isShortage && !isExcess;
                  const isPending = record.status === 'PENDING';

                  return (
                    <tr 
                      key={record.id}
                      onClick={() => setDetailRecord(record)}
                      className="cursor-pointer hover:bg-slate-50 transition-colors group"
                    >
                      {/* Date & Shift */}
                      <td className="py-2 px-3.5 whitespace-nowrap">
                        <div className="flex items-center gap-2">
                          <Calendar className="w-3.5 h-3.5 text-gray-400 shrink-0" />
                          <span className="font-bold text-slate-900">{record.date}</span>
                          <span className="px-1.5 py-0.5 rounded bg-gray-100 text-gray-600 text-[10px] font-mono font-bold">
                            {record.shift_id || 'Shift'}
                          </span>
                        </div>
                        {record.shift_name && (
                          <div className="text-[10px] text-gray-400 font-medium pl-5.5 mt-0.5">
                            {record.shift_name}
                          </div>
                        )}
                      </td>

                      {/* Pumper Name */}
                      <td className="py-2 px-3.5 whitespace-nowrap">
                        <div className="flex items-center gap-2">
                          <div className="w-6 h-6 rounded-full bg-indigo-100 text-indigo-700 flex items-center justify-center font-bold text-[10px]">
                            {record.pumper_name.charAt(0)}
                          </div>
                          <div>
                            <span className="font-bold text-slate-900">{record.pumper_name}</span>
                            {record.notes && (
                              <p className="text-[10px] text-gray-400 truncate max-w-xs">{record.notes}</p>
                            )}
                          </div>
                        </div>
                      </td>

                      {/* Expected Sales */}
                      <td className="py-2 px-3.5 text-right whitespace-nowrap tabular-nums">
                        <span className="font-semibold text-gray-600">
                          Rs. {record.expected_amount.toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                        </span>
                      </td>

                      {/* Actual Handover */}
                      <td className="py-2 px-3.5 text-right whitespace-nowrap tabular-nums">
                        <span className="font-bold text-slate-900">
                          Rs. {record.collected_amount.toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                        </span>
                      </td>

                      {/* Shortage / Excess Badge */}
                      <td className="py-2 px-3.5 text-right whitespace-nowrap tabular-nums">
                        {isShortage ? (
                          <span className="inline-flex items-center gap-1 font-bold text-rose-700 bg-rose-50 px-2 py-0.5 rounded-md border border-rose-200 text-[10.5px]">
                            <TrendingDown className="w-3 h-3 shrink-0" />
                            <span>-Rs. {Math.abs(record.variance_amount).toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
                          </span>
                        ) : isExcess ? (
                          <span className="inline-flex items-center gap-1 font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-200 text-[10.5px]">
                            <TrendingUp className="w-3 h-3 shrink-0" />
                            <span>+Rs. {record.variance_amount.toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 font-bold text-slate-600 bg-gray-100 px-2 py-0.5 rounded text-[10px]">
                            <Check className="w-3 h-3 text-slate-500" />
                            <span>Exact Match (0.00)</span>
                          </span>
                        )}
                      </td>

                      {/* Settlement Status */}
                      <td className="py-2 px-3.5 text-center whitespace-nowrap">
                        {record.status === 'SETTLED' ? (
                          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800 border border-emerald-200">
                            <CheckCircle2 className="w-3 h-3" />
                            <span>Settled</span>
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-amber-100 text-amber-800 border border-amber-200">
                            <Clock className="w-3 h-3" />
                            <span>Pending</span>
                          </span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}
        </div>
      </div>

      {/* Settle Shortage Modal */}
      {settlementModalRecord && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-md w-full p-6 shadow-2xl border border-gray-100 animate-scale-up space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-gray-100">
              <div className="flex items-center gap-2">
                <div className="p-2 bg-indigo-50 text-indigo-600 rounded-xl">
                  <ShieldCheck className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-slate-900">Settle Pumper Shortage</h3>
                  <p className="text-xs text-gray-500">Record cash recovery or supervisor adjustment</p>
                </div>
              </div>
              <button 
                onClick={() => setSettlementModalRecord(null)}
                className="p-1 text-gray-400 hover:text-gray-600 rounded-lg cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="bg-slate-50 p-3.5 rounded-xl border border-slate-200/80 space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-gray-500">Pumper:</span>
                <span className="font-bold text-slate-900">{settlementModalRecord.pumper_name}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Shift ID / Date:</span>
                <span className="font-semibold text-slate-800">{settlementModalRecord.shift_id} • {settlementModalRecord.date}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Expected Sales:</span>
                <span className="font-semibold text-slate-800">Rs. {settlementModalRecord.expected_amount.toFixed(2)}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Handed Over:</span>
                <span className="font-semibold text-slate-800">Rs. {settlementModalRecord.collected_amount.toFixed(2)}</span>
              </div>
              <div className="flex justify-between pt-2 border-t border-slate-200 text-rose-700 font-bold">
                <span>Outstanding Shortage:</span>
                <span className="text-sm">Rs. {Math.abs(settlementModalRecord.variance_amount).toFixed(2)}</span>
              </div>
            </div>

            <form onSubmit={handleConfirmSettlement} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-gray-700 mb-1">
                  Settlement Notes / Recovery Method
                </label>
                <input
                  type="text"
                  placeholder="e.g. Paid in cash, Deducted from salary, Management approved"
                  value={settlementNotes}
                  onChange={(e) => setSettlementNotes(e.target.value)}
                  className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setSettlementModalRecord(null)}
                  className="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 font-bold rounded-xl text-xs transition-all cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmittingSettlement}
                  className="px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl text-xs transition-all cursor-pointer shadow-xs"
                >
                  {isSubmittingSettlement ? 'Saving...' : 'Confirm Settlement'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Manual Balance Entry Modal */}
      {isAddAdjustmentOpen && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-md w-full p-6 shadow-2xl border border-gray-100 animate-scale-up space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-gray-100">
              <div className="flex items-center gap-2">
                <div className="p-2 bg-indigo-50 text-indigo-600 rounded-xl">
                  <Plus className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-slate-900">Record Manual Pumper Balance</h3>
                  <p className="text-xs text-gray-500">Add an offline shift balance or direct adjustment</p>
                </div>
              </div>
              <button 
                onClick={() => setIsAddAdjustmentOpen(false)}
                className="p-1 text-gray-400 hover:text-gray-600 rounded-lg cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleSaveAdjustment} className="space-y-3.5 text-xs">
              <div>
                <label className="block font-bold text-gray-700 mb-1">Select Pumper *</label>
                <select
                  required
                  value={adjustmentForm.pumperId}
                  onChange={(e) => setAdjustmentForm({ ...adjustmentForm, pumperId: e.target.value })}
                  className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                >
                  <option value="">-- Choose Pumper --</option>
                  {pumperList.map(p => (
                    <option key={p.id} value={p.id}>{p.name}</option>
                  ))}
                </select>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-gray-700 mb-1">Date *</label>
                  <input
                    type="date"
                    required
                    value={adjustmentForm.date}
                    onChange={(e) => setAdjustmentForm({ ...adjustmentForm, date: e.target.value })}
                    className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl font-semibold focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block font-bold text-gray-700 mb-1">Shift Ref (Optional)</label>
                  <input
                    type="text"
                    placeholder="e.g. SH-20260928"
                    value={adjustmentForm.shiftId}
                    onChange={(e) => setAdjustmentForm({ ...adjustmentForm, shiftId: e.target.value })}
                    className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl font-semibold focus:outline-none"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-gray-700 mb-1">Expected Sales (Rs.) *</label>
                  <input
                    type="number"
                    step="0.01"
                    required
                    value={adjustmentForm.expectedAmount}
                    onChange={(e) => setAdjustmentForm({ ...adjustmentForm, expectedAmount: Number(e.target.value) })}
                    className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl font-bold tabular-nums focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block font-bold text-gray-700 mb-1">Collected Handover (Rs.) *</label>
                  <input
                    type="number"
                    step="0.01"
                    required
                    value={adjustmentForm.collectedAmount}
                    onChange={(e) => setAdjustmentForm({ ...adjustmentForm, collectedAmount: Number(e.target.value) })}
                    className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl font-bold tabular-nums focus:outline-none"
                  />
                </div>
              </div>

              {/* Computed Preview */}
              <div className="p-3 bg-gray-50 rounded-xl border border-gray-200/80 flex items-center justify-between">
                <span className="font-semibold text-gray-600">Calculated Variance:</span>
                <span className={`font-bold ${
                  adjustmentForm.collectedAmount - adjustmentForm.expectedAmount < -0.5
                    ? 'text-rose-600'
                    : adjustmentForm.collectedAmount - adjustmentForm.expectedAmount > 0.5
                    ? 'text-emerald-600'
                    : 'text-gray-700'
                }`}>
                  Rs. {(adjustmentForm.collectedAmount - adjustmentForm.expectedAmount).toFixed(2)}
                </span>
              </div>

              <div>
                <label className="block font-bold text-gray-700 mb-1">Status</label>
                <select
                  value={adjustmentForm.status}
                  onChange={(e) => setAdjustmentForm({ ...adjustmentForm, status: e.target.value as any })}
                  className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl font-semibold focus:outline-none"
                >
                  <option value="PENDING">Pending Settlement</option>
                  <option value="SETTLED">Settled</option>
                </select>
              </div>

              <div>
                <label className="block font-bold text-gray-700 mb-1">Notes</label>
                <input
                  type="text"
                  placeholder="Additional context or remarks..."
                  value={adjustmentForm.notes}
                  onChange={(e) => setAdjustmentForm({ ...adjustmentForm, notes: e.target.value })}
                  className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl font-medium focus:outline-none"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setIsAddAdjustmentOpen(false)}
                  className="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 font-bold rounded-xl text-xs transition-all cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl text-xs transition-all cursor-pointer shadow-xs"
                >
                  Save Record
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Record Detail Drawer Modal */}
      {detailRecord && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-md w-full p-6 shadow-2xl border border-gray-100 animate-scale-up space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-gray-100">
              <div className="flex items-center gap-2">
                <div className="p-2 bg-indigo-50 text-indigo-600 rounded-xl">
                  <FileText className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-slate-900">Pumper Ledger Breakdown</h3>
                  <p className="text-xs text-gray-500">{detailRecord.shift_id} • {detailRecord.date}</p>
                </div>
              </div>
              <button 
                onClick={() => setDetailRecord(null)}
                className="p-1 text-gray-400 hover:text-gray-600 rounded-lg cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-2.5 text-xs">
              <div className="flex justify-between p-2.5 bg-gray-50 rounded-xl">
                <span className="text-gray-500 font-medium">Pumper Name:</span>
                <span className="font-bold text-slate-900">{detailRecord.pumper_name}</span>
              </div>
              <div className="flex justify-between p-2.5 bg-gray-50 rounded-xl">
                <span className="text-gray-500 font-medium">Expected Sales (Meter + Lubricants):</span>
                <span className="font-bold text-slate-900">Rs. {detailRecord.expected_amount.toLocaleString('en-LK', { minimumFractionDigits: 2 })}</span>
              </div>
              <div className="flex justify-between p-2.5 bg-gray-50 rounded-xl">
                <span className="text-gray-500 font-medium">Total Handover (Cash + Cards + Credit):</span>
                <span className="font-bold text-slate-900">Rs. {detailRecord.collected_amount.toLocaleString('en-LK', { minimumFractionDigits: 2 })}</span>
              </div>
              <div className="flex justify-between p-2.5 bg-gray-50 rounded-xl">
                <span className="text-gray-500 font-medium">Variance (Handover - Expected):</span>
                <span className={`font-bold ${
                  detailRecord.variance_amount < -0.5 ? 'text-rose-600' : detailRecord.variance_amount > 0.5 ? 'text-emerald-600' : 'text-slate-700'
                }`}>
                  {detailRecord.variance_amount >= 0 ? '+' : ''}Rs. {detailRecord.variance_amount.toLocaleString('en-LK', { minimumFractionDigits: 2 })}
                </span>
              </div>
              <div className="flex justify-between p-2.5 bg-gray-50 rounded-xl">
                <span className="text-gray-500 font-medium">Settlement Status:</span>
                <span className="font-bold text-slate-900">{detailRecord.status}</span>
              </div>
              {detailRecord.settled_at && (
                <div className="flex justify-between p-2.5 bg-gray-50 rounded-xl">
                  <span className="text-gray-500 font-medium">Settled On:</span>
                  <span className="font-semibold text-slate-800">{new Date(detailRecord.settled_at).toLocaleString()}</span>
                </div>
              )}
              {detailRecord.settled_by && (
                <div className="flex justify-between p-2.5 bg-gray-50 rounded-xl">
                  <span className="text-gray-500 font-medium">Settled By:</span>
                  <span className="font-semibold text-slate-800">{detailRecord.settled_by}</span>
                </div>
              )}
              {detailRecord.notes && (
                <div className="p-2.5 bg-gray-50 rounded-xl space-y-1">
                  <span className="text-gray-500 font-medium block">Remarks &amp; Audit Notes:</span>
                  <p className="text-slate-800 font-semibold">{detailRecord.notes}</p>
                </div>
              )}
            </div>

            <div className="flex items-center justify-between pt-3 border-t border-gray-100">
              <div>
                {detailRecord.status === 'PENDING' && detailRecord.variance_amount < -0.5 ? (
                  <button
                    onClick={() => {
                      const rec = detailRecord;
                      setDetailRecord(null);
                      setSettlementModalRecord(rec);
                      setSettlementNotes('');
                    }}
                    className="px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl text-xs transition-all cursor-pointer shadow-xs"
                  >
                    Settle Shortage
                  </button>
                ) : detailRecord.status === 'SETTLED' ? (
                  <button
                    onClick={async () => {
                      await handleReopenRecord(detailRecord);
                      setDetailRecord(prev => prev ? { ...prev, status: 'PENDING', settled_at: undefined, settled_by: undefined } : null);
                    }}
                    className="px-3 py-1.5 text-gray-600 hover:text-gray-900 bg-gray-100 hover:bg-gray-200 font-bold rounded-xl text-xs transition-all cursor-pointer"
                  >
                    Reopen Record
                  </button>
                ) : null}
              </div>
              <button
                onClick={() => setDetailRecord(null)}
                className="px-4 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-700 font-bold rounded-xl text-xs cursor-pointer"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
